[server]
# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
;root_url = %(protocol)s://%(domain)s:%(http_port)s/
root_url = https://sqlmonitor.ajaydwivedi.com/

[auth]
# Use email lookup in addition to the unique ID provided by the IdP
oauth_allow_insecure_email_lookup = true

[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

# specify role for unauthenticated users
org_role = Viewer

[auth.github]
enabled = true
allow_sign_up = true
client_id = <GITHUB_OAUTH_CLIENT_ID>
client_secret = <GITHUB_OAUTH_CLIENT_SECRET>
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user

[auth.google]
enabled = true
allow_sign_up = true
client_id = <GOOGLE_OAUTH_CLIENT_ID>
client_secret = <GOOGLE_OAUTH_CLIENT_SECRET>
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token

[smtp]
enabled = true
host = smtp.gmail.com:587
user = <SMTP_USERNAME_OR_EMAIL>
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = <SMTP_PASSWORD_OR_APP_PASSWORD>
skip_verify = true
from_address = <SMTP_FROM_ADDRESS>
from_name = Grafana