apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: http
spec:
  type: NodePort
  selector:
    app: httpd_app
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: http
  labels:
    app: httpd_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app
  template:
    metadata:
      labels:
        app: httpd_app
    spec:
      containers:
        - name: httpd-container-devops
          image: httpd:latest
          ports:
            - containerPort: 80
